[package]
name = "gdbmi"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]


[[bin]]
doc = false
name = "gdbmi"

[dependencies]
lazy_static = "0.2.2"
#pty and gdbmi
nix = "^0.7"
#gdbmi
nom = "^1.2"
#unsegen
termion = "^1.1"
ndarray = "0.6"
smallvec = "0.3"
unicode-segmentation = "1.0"
unicode-width = "0.1"
#pty
libc = "^0.2"

#[dependencies.termion]
#git = "https://github.com/Ticki/termion"
#features = ["nightly"]

#[dependencies.termion]
#path = "../termion/"
#features = ["nightly"]
