[package]
name = "ugdb"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]
description = "An unsegen-based GDB frontend."

[[bin]]
doc = false
name = "ugdb"

[dependencies]
chan = "0.1"
chan-signal = "0.3"
structopt = "0.2.1"
time = "0.1"

# For IPC
json = "0.11"
rand = "0.3"
unix_socket = "0.5"

[dependencies.unsegen]
git = "https://github.com/ftilde/unsegen"
#path = "../unsegen"

[dependencies.unsegen-signals]
git = "https://github.com/ftilde/unsegen"
#path = "../unsegen/unsegen-signals"

[dependencies.unsegen-terminal]
git = "https://github.com/ftilde/unsegen"
#path = "../unsegen/unsegen-terminal"

[dependencies.unsegen-pager]
git = "https://github.com/ftilde/unsegen"
#path = "../unsegen/unsegen-pager"

# For ExpressionTable
[dependencies.unsegen-jsonviewer]
git = "https://github.com/ftilde/unsegen"
#path = "../unsegen/unsegen-jsonviewer"

[dependencies.gdb-expression-parsing]
path = "gdb-expression-parsing"

[dependencies.gdbmi]
path = "gdbmi-rs/"

[build-dependencies]
git2 = "0.6"
toml = "0.4"
lalrpop = "0.14.0"

[workspace]
