[package]
name = "ugdb"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]
description = "An unsegen-based GDB frontend."

[[bin]]
doc = false
name = "ugdb"

[profile.release]
debug = true

[dependencies]
chan = "0.1"
chan-signal = "0.3"
structopt = "0.2.1"
time = "0.1"
unicode-width = "0.1"

# For IPC
json = "0.11"
rand = "0.3"
unix_socket = "0.5"

# For ExpressionTable (gdb expression parsing)
lalrpop-util = "0.14.0"

#unsegen
syntect = "1.0"

[dependencies.unsegen]
path = "unsegen/"

[dependencies.unsegen-signals]
path = "unsegen-signals"

[dependencies.unsegen-terminal]
path = "unsegen-terminal"

# For ExpressionTable
[dependencies.unsegen-jsonviewer]
path = "unsegen-jsonviewer"

[dependencies.gdbmi]
path = "gdbmi-rs/"

[build-dependencies]
git2 = "0.6"
toml = "0.4"
lalrpop = "0.14.0"

[workspace]
