[package]
name = "ugdb"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]

[[bin]]
doc = false
name = "ugdb"

[profile.release]
debug = true

[dependencies]
chan = "^0.1"
chan-signal = "^0.2"
lazy_static = "0.2.2"
unicode-width = "0.1"
#pty
nix = "^0.7"
libc = "^0.2"

#unsegen
syntect = "1.0"
termion = "^1.3"
#[dependencies.termion]
#git = "https://github.com/ftilde/termion"

[dependencies.unsegen]
path = "unsegen/"

[dependencies.gdbmi]
path = "gdbmi-rs/"
