[package]
name = "gdbmi"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]


[[bin]]
doc = false
name = "gdbmi"

[dependencies]
lazy_static = "0.2.2"
#pty and gdbmi
nix = "^0.7"
#gdbmi
nom = "^2.1"
#pty
libc = "^0.2"

#unsegen
syntect = "1.0"
[dependencies.termion]
git = "https://github.com/ftilde/termion"
[dependencies.unsegen]
path = "unsegen/"
